"""
URL configuration for fundo project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# backend/fundo/urls.py
# backend/fundo/urls.py

# backend/fundo/urls.py

from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework.routers import DefaultRouter

# Consolidated Imports for all your custom views from core.views
from core.views import (
    UserProfileViewSet,
    CategoryViewSet,
    ProjectViewSet,
    DonationViewSet,
    CommentViewSet,
    UserCreateView, # <-- Make sure UserCreateView is included here
)

# --- AJOUTEZ CETTE LIGNE ---
from graphene_django.views import GraphQLView
# --- ET CELLE-CI POUR VOTRE SCHEMA ---
from core.schema import schema # Assurez-vous que le chemin est correct pour votre schema.py
#from graphene_django.views import GraphQLView
#from graphql_jwt.decorators import jwt_cookie, jwt_token 
from django.views.decorators.csrf import csrf_exempt

# Initialize the router ONCE and register ALL ViewSets
router = DefaultRouter()
router.register(r'profiles', UserProfileViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'projects', ProjectViewSet)
router.register(r'donations', DonationViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),

    # JWT Authentication Endpoints
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Custom User Registration Endpoint
    path('api/register/', UserCreateView.as_view(), name='register'), # This will now be visible

    # Include all API endpoints generated by the router
    path('api/', include(router.urls)), # This must be after 'api/register/' if you want it to appear separately at the root
    # NEW: URL for comments nested under a specific project
    # This will allow GET requests to /api/projects/<project_id>/comments/
    path('api/projects/<int:project_pk>/comments/',
         CommentViewSet.as_view({'get': 'list'}),
         name='project-comments'),
    # Endpoint GraphQL
    #path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
    #path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),


        # path('graphql/', jwt_token(jwt_cookie(GraphQLView.as_view(graphiql=True))), name='graphql'),
]

# For serving media files in development (MUST BE AT THE VERY END OF THE FILE)
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)